[package]
name = "ds210_final"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.1"
rand = "0.8.5"
gnuplot = "0.0.37"
petgraph = "0.6.3"
plotters = "0.3.4"